language: go
os:
  - linux
arch:
  - amd64
  - ppc64le
go:
  - 1.10
  - tip
sudo: false
install:
  - mkdir -p $HOME/gopath/src/gopkg.in/hlandau/
  - ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/gopkg.in/hlandau/passlib.v1
  - cd $HOME/gopath/src/gopkg.in/hlandau/passlib.v1
  - go get
